ThingSet/thingset-zephyr-sdk

Kconfig
This is useful for applications with lots of data objects or data objects with large arrays.
=> Increase maximum allowed shared TX buf size

src/can.c
If the CAN bus is down/disconnected, `thingset_can_init` blocks forever, so system initialisation never completes. This change moves initialisation back to the thread so that it does not block system initialisation. If the CAN bus is subsequently connected, the initialisation method will then complete.
=> CAN: don't use SYS_INIT as it will block forever if CAN bus is down

include/thingset/can.h, include/thingset/isotp_fast.h, src/Kconfig.can, src/can.c, src/isotp_fast.c, src/isotp_fast_internal.h, tests/can/src/main.c, tests/isotp_fast/conformance/src/async_recv.h, tests/isotp_fast/conformance/src/main.c, tests/isotp_fast/conformance/src/main.h, tests/isotp_fast/conformance/src/sync_recv.h, tests/isotp_fast/conformance/testcase.yaml
This PR implements the new bus numbering scheme to overcome issues with overlapping filters for gateways.
Related specification update: https://github.com/ThingSet/thingset.github.io/issues/25
=> CAN: Implement new bus numbering scheme

src/can.c
Moved the semaphore unlock statement outside the `#endif` directive in `can.c`. This ensures proper unlocking of the semaphore for both cases, whether `CONFIG_THINGSET_CAN_PACKETIZED_REPORTS_TX` is enabled or not. Resolves the issue of warning and failure in TX CAN communication when the configuration is disabled.
Fixes #12.
=> CAN: Fix semaphore unlock in the report tx handler

include/canbus/isotp_fast.h, include/thingset/can.h, src/Kconfig.can, src/can.c, subsys/canbus/isotp_fast/isotp_fast.c, subsys/canbus/isotp_fast/isotp_fast_internal.h, tests/can/src/main.c
The bus numbering scheme introduced in #11 only supports up to 16 different buses in a system.
This PR adds an alternative routing method based on bridges. One bridge defines routing between exactly two buses. If it is not required to send data from any bus to any other bus, the bridge concept allows to have more buses in one system, especially if the bus layout is hierarchical. The maximum number of bridges is 255.
The existing routing based on bus numbers is selected as the default. The bridge-based routing is enabled with `CONFIG_THINGSET_CAN_ROUTING_BRIDGES`.
In addition to the implementation of the bridge routing, some clean-ups and bugfixes for ISO-TP are included in the PR.
=> CAN: Add bridge routing and fix some ISO-TP issues

include/thingset/can.h, src/can.c, tests/can/prj.conf, tests/can/src/main.c
Related PR for spec: https://github.com/ThingSet/thingset.github.io/pull/30
If time permits, I will add more unit tests to improve the test coverage including edge cases and errors.
=> CAN: Rework multi-frame reports to include MF type

tests/storage_eeprom/CMakeLists.txt, tests/storage_eeprom/boards/native_posix.overlay, tests/storage_eeprom/boards/native_posix_64.overlay, tests/storage_eeprom/boards/native_sim.conf, tests/storage_eeprom/boards/native_sim.overlay, tests/storage_eeprom/prj.conf, tests/storage_eeprom/src/main.c, tests/storage_eeprom/testcase.yaml
The emulated at24 EEPROM with `native_sim` fails for unknown reasons, so I disabled it for CI, but kept the code.
=> EEPROM storage: Add simple unit tests

src/Kconfig.storage, src/sdk.c
Depending on the environment, loading data from e.g. an I2C EEPROM may fail occasionally with bad CRCs due to noise in the communication.
This PR allows to attempt to read the data multiple times and makes the number of attempts configurable via Kconfig.
=> Storage: Use multiple attempts to load data

src/Kconfig.can, src/Kconfig.storage, src/storage_eeprom.c, tests/storage_eeprom/testcase.yaml, west.yml
This allows data larger than the shared buffer size to be loaded from/saved to EEPROM. The only requirement is that the buffer be large enough to hold the largest single key-value pair in the stored data (i.e. it cannot loads part of an array over separate reads).
=> Support reading and writing data larger than shared buffer to EEPROM

src/storage_eeprom.c
Read 128 byte chunks from EEPROM as reads get very large when many items added to ThingSet.
=> EEPROM: add smaller eeprom reads

src/Kconfig.storage, src/storage_eeprom.c, tests/storage_eeprom/src/main.c, tests/storage_eeprom/testcase.yaml
If enabled, the available EEPROM memory is divided into two equal sections and that data is always written to both sections each time. This allows to recover from power failures because at least one section will always have valid data.
=> EEPROM: Add option to store data twice to improve reliability

tests/storage_eeprom/src/main.c, west.yml
This PR adds some additional data to ThingSet such that progressive import/export is necessary because the data does not fit into the 1024 byte buffer anymore.
When adding the tests, some issues in the node lib were discovered, which are fixed by bumping the version in west.yml.
=> Cover progressive import/export in unit tests

src/Kconfig.storage, src/storage_eeprom.c
Verifies EEPROM writes and chunks them using the same size as used for reads.
=> EEPROM writes should be verified

src/storage_common.c
same problem as in https://github.com/ThingSet/thingset-node-c/commit/d118db0c6fcf55cc3518e82c9e410ad15ec7920f #ifdefs needed because linker links files which are not compiled when CONFIG_THINGSET_STORAGE_AUTOSAVE=n
=> #ifdefs needed, IS_ENABLED(...) does not work at compile time

src/storage_eeprom.c
Simple change to prevent this warning message
```
thingset-zephyr-sdk/src/storage_eeprom.c:227:22: warning: 'err' may be used uninitialized [-Wmaybe-uninitialized]
227 |     } while (rtn > 0 && err == 0);
```
=> Initialise err to 0 to avoid -Wmaybe-uninitialized

Kconfig, src/sdk.c
sys_rand32_get() seems to return the same sequence when spooling up multiple thingset duplicate POSIX applications. This uses the task PID instead.
=> Added option to use task PID for EUI seed under native POSIX

src/can.c
Add name of CAN device to printout to make clearer when multiple CAN devices are in use
=> Add can device name to address claim printout

include/thingset/sdk.h, src/Kconfig.lorawan, src/lorawan.c
End device activation support for Activation By Personalization(ABP). Default ABP is disabled, set LoRaWAN data object pAbp to true to enable ABP and device address(pDevAddr), session keys for network(pNwkSKey) and application(pAppSKey).
Testing with Chirpstack network server for both OTAA and ABP can work fine.
=> LoRaWAN: support ABP activation

src/can.c
A few things here:
- request/response timer should start straight away rather than after `timeout`
- the CAN ID should be passed to the request/response sent callback (rather than `0`)
- the sent callback should be called on success, not just on failure
=> CAN: Request/response fixes

include/thingset/can.h, src/can.c
Add an (optional) timeout on CAN initialisation.
=> CAN: Initialisation Timeout
